name: Flush CDN After Merge

on:
  push:
    branches: [ main,testing ]

  workflow_dispatch:
    

jobs:
  flush-cdn-after-merge:
    runs-on: ubuntu-latest
    
    steps:

    - name: Flush CDN after merge
      env:
        BUNNY_PULLZONE_ID: ${{ secrets.BUNNY_PULLZONE_ID }}
        BUNNY_ACCESS_KEY: ${{ secrets.BUNNY_ACCESS_KEY }}
      run: |
        sleep 90 # Wait for the CDN to be updated
        curl -v --request POST \
            --url "https://api.bunny.net/pullzone/$BUNNY_PULLZONE_ID/purgeCache" \
            --header "AccessKey: $BUNNY_ACCESS_KEY" \
            --header 'content-type: application/json'
        sleep 60 # Wait for the CDN to be updated
        curl -v --request POST \
            --url "https://api.bunny.net/pullzone/$BUNNY_PULLZONE_ID/purgeCache" \
            --header "AccessKey: $BUNNY_ACCESS_KEY" \
            --header 'content-type: application/json'

        




# Purging the CDN curl command
# curl --request POST \
#     --url https://api.bunny.net/pullzone/${{ secrets.BUNNY_PULLZONE_ID }}/purgeCache \
#     --header 'AccessKey: ${{ secrets.BUNNY_ACCESS_KEY }}' \
#     --header 'content-type: application/json'
#
